spring:
  data:
    elasticsearch:
      # elasticsearch集群名称，默认的是elasticsearch
      cluster-name: elasticsearch
      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
      cluster-nodes: 192.168.25.150:9300
      #是否开启本地存储
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/es?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
mybatis:
  configuration:
    map-underscore-to-camel-case: true